# Generated by Django 5.0.6 on 2024-06-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_trailers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trailers',
        ),
    ]
