# Generated by Django 5.0.6 on 2024-06-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_trailer_enabled_for_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('load_id', models.IntegerField(primary_key=True, serialize=False)),
                ('load_number', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('appointment_time', models.DateTimeField()),
                ('miles_left', models.IntegerField()),
                ('rate', models.FloatField()),
                ('penalties', models.TextField()),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='telegram_bot.driver')),
                ('assigned_trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='telegram_bot.trailer')),
            ],
        ),
    ]
