# Generated by Django 5.0.6 on 2024-06-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_driver_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
