# Generated by Django 5.0.6 on 2024-06-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_trailer_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
