# Generated by Django 5.0.6 on 2024-06-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_driver_telegram_chat_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Load',
        ),
    ]
