# Generated by Django 5.0.6 on 2024-06-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_delete_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.CharField(max_length=100)),
                ('delivery_location', models.TextField()),
                ('delivery_time', models.DateTimeField()),
                ('assigned_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='telegram_bot.driver')),
            ],
        ),
    ]
