# Generated by Django 5.0.6 on 2024-06-24 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_load_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='assigned_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='telegram_bot.trailer'),
        ),
    ]
