# Generated by Django 5.0.6 on 2024-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_load_assigned_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_group_name', models.CharField(max_length=200)),
                ('group_chat_id', models.CharField(max_length=200)),
            ],
        ),
    ]
