# Generated by Django 5.0.6 on 2024-06-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_broker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='group_chat_id',
            new_name='telegram_chat_id',
        ),
    ]
