# Generated by Django 5.0.6 on 2024-06-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_rename_group_chat_id_broker_telegram_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='broker_group_name',
            new_name='name',
        ),
    ]
