# Generated by Django 5.0.6 on 2024-06-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_rename_broker_group_name_broker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
