# Generated by Django 5.0.6 on 2024-06-25 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0015_alter_load_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='assigned_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_driver', to='telegram_bot.driver'),
        ),
    ]
