# Generated by Django 5.0.6 on 2024-06-25 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0021_alter_load_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='assigned_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='telegram_bot.trailer'),
        ),
    ]
