# Generated by Django 5.0.6 on 2024-06-25 20:54

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0023_remove_load_actual_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
