# Generated by Django 5.0.6 on 2024-06-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0024_trailer_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='timezone',
        ),
    ]
