# Generated by Django 5.0.6 on 2024-06-25 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0026_alter_load_assigned_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='assigned_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads_broker', to='telegram_bot.broker'),
        ),
    ]
