# Generated by Django 5.0.6 on 2024-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0027_alter_load_assigned_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamsaraToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
